### ISSUE TITLE
Home of lmodel2

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/lmodel2#1]
@vegandevs/owners  @legendre  @philippec : I have maintained **R** package **lmodel2** during its lifetime in CRAN. After initial adaptation to **R** this has been very low-intensity maintenance: no real development has been made, but the package has been adapted to changes in CRAN requirements. I currently noticed that one such change again happened: the `import`  requirements were made more stringent in CRAN, and most packages must change their `NAMESPACE`  file. Therefore I moved  **lmodel2** from R-Forge to GitHub and vegandevs group. I made the minimal fix (a0300ab050ebef0d6046143b4259f5e67dce78e5), and I could now release this functionally unchanged package to CRAN. However, I'm not sure that vegandevs is the optimal location or that I am the optimal maintainer -- I really only _maintain_, but I do not _develop_ the code. Would you like to take over the package maintenance for CRAN? It is now in GitHub so that moving the package from vegandevs to some other home would be very easy. Maintenance only needs following CRAN guidelines (hmm...) and familiarity with **R** programming and with git.

**Comment by philippec** [comment]
@jarioksa I think that between @legendre and I we should be able to do that. Certainly I can help with any issue arising from git / github, and @legendre is more than familiar with R :-)

Can you clarify what you had in mind? Would lmodel move from vegandevs to another home? It's kind of handy to have it within vegandevs, but are you worried that the permissions are not granular enough to allow for a separate maintainer for a sub-package? How does it feed back into CRAN? I am unfamiliar with that particular aspect / workflow.
